import type { FieldDef } from '../components/admin/fields';

// Field definitions for every CMS collection. Drives the generic CRUD editor.
export const FIELD_CONFIGS: Record<string, { fields: FieldDef[]; title: string; subtitle?: string; searchKeys?: string[]; objectListFields?: { name: string; label: string; fields: { name: string; label: string }[] }[] }> = {
  skills: {
    title: 'Skills', subtitle: 'Manage technical skills grouped by category.',
    searchKeys: ['name', 'category'],
    fields: [
      { name: 'name', label: 'Skill Name', type: 'text' },
      { name: 'category', label: 'Category', type: 'select', options: ['Backend', 'Frontend', 'Database', 'Cloud', 'DevOps', 'Tools', 'Languages'] },
      { name: 'level', label: 'Proficiency (0-100)', type: 'number' },
      { name: 'icon', label: 'Icon (emoji)', type: 'text' },
      { name: 'color', label: 'Color', type: 'color' },
    ],
  },
  education: {
    title: 'Education', subtitle: 'Academic qualifications timeline.',
    searchKeys: ['institution', 'degree'],
    fields: [
      { name: 'institution', label: 'Institution', type: 'text', full: true },
      { name: 'logo_url', label: 'Logo URL', type: 'image' },
      { name: 'degree', label: 'Degree', type: 'text' },
      { name: 'field', label: 'Field', type: 'text' },
      { name: 'start_date', label: 'Start Date', type: 'text' },
      { name: 'end_date', label: 'End Date', type: 'text' },
      { name: 'cgpa', label: 'CGPA', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
    ],
  },
  experience: {
    title: 'Experience', subtitle: 'Work history and internships.',
    searchKeys: ['company', 'role'],
    fields: [
      { name: 'company', label: 'Company', type: 'text' },
      { name: 'logo_url', label: 'Logo URL', type: 'image' },
      { name: 'role', label: 'Role', type: 'text' },
      { name: 'type', label: 'Type', type: 'select', options: ['Full-time', 'Internship', 'Part-time', 'Freelance'] },
      { name: 'start_date', label: 'Start', type: 'text' },
      { name: 'end_date', label: 'End', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
      { name: 'achievements', label: 'Achievements', type: 'array', full: true, placeholder: 'Add achievement...' },
    ],
  },
  projects: {
    title: 'Projects', subtitle: 'Showcase your work.',
    searchKeys: ['title', 'technologies'],
    fields: [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'short_description', label: 'Short Description', type: 'textarea', full: true },
      { name: 'detailed_description', label: 'Detailed Description', type: 'textarea', full: true },
      { name: 'image_url', label: 'Cover Image', type: 'image', full: true },
      { name: 'screenshots', label: 'Screenshots', type: 'array', full: true, placeholder: 'Add screenshot URL...' },
      { name: 'demo_video_url', label: 'Demo Video URL', type: 'text', full: true },
      { name: 'architecture_diagram_url', label: 'Architecture Diagram URL', type: 'image', full: true },
      { name: 'features', label: 'Features', type: 'array', full: true },
      { name: 'challenges', label: 'Challenges', type: 'array', full: true },
      { name: 'learnings', label: 'Learnings', type: 'array', full: true },
      { name: 'technologies', label: 'Technologies', type: 'array', full: true },
      { name: 'github_url', label: 'GitHub URL', type: 'text', full: true },
      { name: 'live_url', label: 'Live URL', type: 'text', full: true },
      { name: 'featured', label: 'Featured', type: 'checkbox' },
    ],
  },
  certificates: {
    title: 'Certificates', subtitle: 'Professional certifications.',
    searchKeys: ['name', 'organization'],
    fields: [
      { name: 'name', label: 'Certificate Name', type: 'text', full: true },
      { name: 'organization', label: 'Organization', type: 'text' },
      { name: 'logo_url', label: 'Org Logo', type: 'image' },
      { name: 'image_url', label: 'Certificate Image', type: 'image', full: true },
      { name: 'credential_id', label: 'Credential ID', type: 'text' },
      { name: 'issue_date', label: 'Issue Date', type: 'text' },
      { name: 'verification_url', label: 'Verification URL', type: 'text', full: true },
      { name: 'skills', label: 'Skills', type: 'array', full: true },
    ],
  },
  achievements: {
    title: 'Achievements', subtitle: 'Awards, hackathons, workshops.',
    searchKeys: ['title', 'type'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', full: true },
      { name: 'type', label: 'Type', type: 'select', options: ['Award', 'Hackathon', 'Competition', 'Workshop', 'Seminar', 'Internship', 'Publication', 'Certification', 'Achievement', 'Volunteer', 'Leadership', 'Organization'] },
      { name: 'organization', label: 'Organization', type: 'text' },
      { name: 'date', label: 'Date', type: 'text' },
      { name: 'icon', label: 'Icon (emoji)', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
    ],
  },
  gallery: {
    title: 'Gallery', subtitle: 'Photos organized by category.',
    searchKeys: ['title', 'category'],
    fields: [
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'image_url', label: 'Image', type: 'image', full: true },
      { name: 'category', label: 'Category', type: 'select', options: ['Certificates', 'Events', 'College', 'Projects', 'Personal'] },
      { name: 'date', label: 'Date', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea', full: true },
    ],
  },
  testimonials: {
    title: 'Testimonials', subtitle: 'Recommendations.',
    searchKeys: ['name', 'company'],
    fields: [
      { name: 'name', label: 'Name', type: 'text' },
      { name: 'role', label: 'Role', type: 'text' },
      { name: 'company', label: 'Company', type: 'text' },
      { name: 'avatar_url', label: 'Avatar', type: 'image' },
      { name: 'quote', label: 'Quote', type: 'textarea', full: true },
      { name: 'rating', label: 'Rating (1-5)', type: 'number' },
    ],
  },
  blogs: {
    title: 'Blogs', subtitle: 'Articles and writing.',
    searchKeys: ['title', 'tags'],
    fields: [
      { name: 'title', label: 'Title', type: 'text', full: true },
      { name: 'slug', label: 'Slug', type: 'text' },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea', full: true },
      { name: 'content', label: 'Content', type: 'textarea', full: true },
      { name: 'cover_url', label: 'Cover Image', type: 'image', full: true },
      { name: 'tags', label: 'Tags', type: 'array', full: true },
      { name: 'published', label: 'Published', type: 'checkbox' },
      { name: 'read_time', label: 'Read Time (min)', type: 'number' },
    ],
  },
  coding_profiles: {
    title: 'Coding Profiles', subtitle: 'LeetCode, GitHub, etc.',
    searchKeys: ['platform', 'username'],
    fields: [
      { name: 'platform', label: 'Platform', type: 'text' },
      { name: 'username', label: 'Username', type: 'text' },
      { name: 'url', label: 'Profile URL', type: 'text', full: true },
      { name: 'icon', label: 'Icon (emoji)', type: 'text' },
      { name: 'stats', label: 'Stats', type: 'objectlist', full: true },
    ],
    objectListFields: [{ name: 'stats', label: 'Stats', fields: [{ name: 'label', label: 'Label' }, { name: 'value', label: 'Value' }] }],
  },
  social_links: {
    title: 'Social Links', subtitle: 'Social media profiles.',
    searchKeys: ['platform'],
    fields: [
      { name: 'platform', label: 'Platform', type: 'text' },
      { name: 'url', label: 'URL', type: 'text', full: true },
      { name: 'icon', label: 'Icon (Github, Linkedin, Twitter, Mail)', type: 'text' },
    ],
  },
};

export const SINGLETON_CONFIGS: Record<string, { fields: FieldDef[]; title: string; subtitle?: string; objectListFields?: { name: string; label: string; fields: { name: string; label: string }[] }[] }> = {
  profile: {
    title: 'Profile', subtitle: 'Your core identity and contact info.',
    fields: [
      { name: 'name', label: 'Full Name', type: 'text' },
      { name: 'role', label: 'Professional Title', type: 'text' },
      { name: 'tagline', label: 'Tagline', type: 'text', full: true },
      { name: 'email', label: 'Email', type: 'text' },
      { name: 'phone', label: 'Phone', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
      { name: 'photo_url', label: 'Profile Photo', type: 'image', full: true },
      { name: 'github_username', label: 'GitHub Username', type: 'text' },
      { name: 'years_experience', label: 'Years of Experience', type: 'number' },
      { name: 'availability', label: 'Availability', type: 'select', options: ['available', 'open', 'busy', 'unavailable'] },
      { name: 'availability_note', label: 'Availability Note', type: 'text', full: true },
      { name: 'typing_roles', label: 'Typing Roles', type: 'array', full: true, placeholder: 'Add role...' },
    ],
  },
  hero: {
    title: 'Hero Section', subtitle: 'The first thing visitors see.',
    fields: [
      { name: 'heading', label: 'Heading', type: 'text', full: true },
      { name: 'subheading', label: 'Subheading', type: 'textarea', full: true },
      { name: 'primary_cta_label', label: 'Primary Button Label', type: 'text' },
      { name: 'primary_cta_href', label: 'Primary Button Link', type: 'text' },
      { name: 'secondary_cta_label', label: 'Secondary Button Label', type: 'text' },
      { name: 'secondary_cta_href', label: 'Secondary Button Link', type: 'text' },
      { name: 'show_voice_assistant', label: 'Show AI Voice Assistant', type: 'checkbox' },
      { name: 'background_effect', label: 'Background Effect', type: 'select', options: ['particles', 'aurora', 'grid'] },
    ],
  },
  about: {
    title: 'About Me', subtitle: 'Your professional introduction.',
    fields: [
      { name: 'headline', label: 'Headline', type: 'text', full: true },
      { name: 'paragraphs', label: 'Paragraphs', type: 'array', full: true, placeholder: 'Add paragraph...' },
      { name: 'highlights', label: 'Highlights', type: 'objectlist', full: true },
      { name: 'facts', label: 'Quick Facts', type: 'objectlist', full: true },
    ],
    objectListFields: [
      { name: 'highlights', label: 'Highlights', fields: [{ name: 'label', label: 'Label' }, { name: 'value', label: 'Value' }] },
      { name: 'facts', label: 'Facts', fields: [{ name: 'label', label: 'Label' }, { name: 'value', label: 'Value' }] },
    ],
  },
  resume: {
    title: 'Resume', subtitle: 'Upload your resume PDF or image. File name and size update automatically.',
    fields: [
      { name: 'file_url', label: 'Resume File (upload PDF, JPG, PNG — or paste URL)', type: 'file', full: true },
      { name: 'file_name', label: 'File Name (auto-filled on upload)', type: 'text', readOnly: true },
      { name: 'file_size', label: 'File Size (auto-filled on upload)', type: 'text', readOnly: true },
    ],
  },
  settings: {
    title: 'Settings', subtitle: 'SEO, theme, and global configuration.',
    fields: [
      { name: 'site_title', label: 'Site Title', type: 'text', full: true },
      { name: 'site_description', label: 'Site Description', type: 'textarea', full: true },
      { name: 'primary_color', label: 'Primary Color', type: 'color' },
      { name: 'accent_color', label: 'Accent Color', type: 'color' },
      { name: 'font', label: 'Font Family', type: 'text' },
      { name: 'seo_title', label: 'SEO Title', type: 'text', full: true },
      { name: 'seo_description', label: 'SEO Description', type: 'textarea', full: true },
      { name: 'seo_keywords', label: 'SEO Keywords', type: 'textarea', full: true },
      { name: 'og_image', label: 'OG Image', type: 'image', full: true },
      { name: 'analytics_enabled', label: 'Analytics Enabled', type: 'checkbox' },
    ],
  },
};
